const dinnerMenusKo = [
        { name: "김치찌개", cuisine: "한식", moods: ["든든한", "따뜻한", "매운"], emoji: "🍲" },
        { name: "비빔밥", cuisine: "한식", moods: ["든든한", "가벼운"], emoji: "🥗" },
        { name: "삼겹살", cuisine: "한식", moods: ["든든한"], emoji: "🥓" },
        { name: "칼국수", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🍜" },
        { name: "된장찌개", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🥘" },
        { name: "순두부찌개", cuisine: "한식", moods: ["따뜻한", "매운"], emoji: "🍲" },
        { name: "제육볶음", cuisine: "한식", moods: ["든든한", "매운"], emoji: "🔥" },
        { name: "닭갈비", cuisine: "한식", moods: ["든든한", "매운"], emoji: "🍗" },
        { name: "갈비탕", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🍖" },
        { name: "보쌈", cuisine: "한식", moods: ["든든한"], emoji: "🥬" },
        { name: "불고기덮밥", cuisine: "한식", moods: ["든든한"], emoji: "🍚" },
        { name: "냉면", cuisine: "한식", moods: ["가벼운"], emoji: "🧊" },
        { name: "마라탕", cuisine: "중식", moods: ["매운", "든든한"], emoji: "🥘" },
        { name: "짜장면", cuisine: "중식", moods: ["든든한"], emoji: "🍝" },
        { name: "짬뽕", cuisine: "중식", moods: ["매운", "따뜻한"], emoji: "🍜" },
        { name: "탕수육", cuisine: "중식", moods: ["든든한"], emoji: "🍤" },
        { name: "볶음밥", cuisine: "중식", moods: ["든든한"], emoji: "🍳" },
        { name: "마파두부덮밥", cuisine: "중식", moods: ["매운", "든든한"], emoji: "🥡" },
        { name: "깐풍기", cuisine: "중식", moods: ["매운", "든든한"], emoji: "🍗" },
        { name: "유린기", cuisine: "중식", moods: ["가벼운"], emoji: "🥗" },
        { name: "양장피", cuisine: "중식", moods: ["가벼운"], emoji: "🥢" },
        { name: "초밥", cuisine: "일식", moods: ["가벼운"], emoji: "🍣" },
        { name: "돈카츠", cuisine: "일식", moods: ["든든한"], emoji: "🍛" },
        { name: "라멘", cuisine: "일식", moods: ["따뜻한", "든든한"], emoji: "🍜" },
        { name: "우동", cuisine: "일식", moods: ["따뜻한", "가벼운"], emoji: "🥢" },
        { name: "가츠동", cuisine: "일식", moods: ["든든한"], emoji: "🍚" },
        { name: "오야코동", cuisine: "일식", moods: ["든든한", "따뜻한"], emoji: "🐣" },
        { name: "규동", cuisine: "일식", moods: ["든든한"], emoji: "🥩" },
        { name: "메밀소바", cuisine: "일식", moods: ["가벼운"], emoji: "🍜" },
        { name: "사케동", cuisine: "일식", moods: ["가벼운", "든든한"], emoji: "🐟" },
        { name: "파스타", cuisine: "양식", moods: ["가벼운", "든든한"], emoji: "🍝" },
        { name: "스테이크", cuisine: "양식", moods: ["든든한"], emoji: "🥩" },
        { name: "리조또", cuisine: "양식", moods: ["따뜻한"], emoji: "🍚" },
        { name: "샐러드 볼", cuisine: "양식", moods: ["가벼운"], emoji: "🥗" },
        { name: "피자", cuisine: "양식", moods: ["든든한"], emoji: "🍕" },
        { name: "라자냐", cuisine: "양식", moods: ["든든한", "따뜻한"], emoji: "🧀" },
        { name: "함박스테이크", cuisine: "양식", moods: ["든든한"], emoji: "🍖" },
        { name: "치킨 시저 샐러드", cuisine: "양식", moods: ["가벼운"], emoji: "🥬" },
        { name: "크림수프와 브레드", cuisine: "양식", moods: ["따뜻한", "가벼운"], emoji: "🍞" },
        { name: "떡볶이", cuisine: "분식", moods: ["매운", "든든한"], emoji: "🌶️" },
        { name: "김밥", cuisine: "분식", moods: ["가벼운"], emoji: "🍙" },
        { name: "라볶이", cuisine: "분식", moods: ["매운", "따뜻한"], emoji: "🍲" },
        { name: "순대", cuisine: "분식", moods: ["든든한"], emoji: "🍢" },
        { name: "튀김 모둠", cuisine: "분식", moods: ["든든한"], emoji: "🍤" },
        { name: "쫄면", cuisine: "분식", moods: ["매운", "가벼운"], emoji: "🍜" },
        { name: "어묵탕", cuisine: "분식", moods: ["따뜻한"], emoji: "🍢" },
        { name: "치즈라면", cuisine: "분식", moods: ["따뜻한", "든든한"], emoji: "🧀" },
        { name: "햄버거", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🍔" },
        { name: "치킨", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🍗" },
        { name: "샌드위치", cuisine: "패스트푸드", moods: ["가벼운"], emoji: "🥪" },
        { name: "핫도그", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🌭" },
        { name: "타코", cuisine: "패스트푸드", moods: ["매운", "가벼운"], emoji: "🌮" },
        { name: "부리토", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🌯" },
        { name: "치킨버거", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🍔" },
        { name: "부대찌개", cuisine: "한식", moods: ["든든한", "따뜻한", "매운"], emoji: "🍲" },
        { name: "설렁탕", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🥣" },
        { name: "육개장", cuisine: "한식", moods: ["따뜻한", "매운", "든든한"], emoji: "🌶️" },
        { name: "순대국밥", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🍜" },
        { name: "콩나물국밥", cuisine: "한식", moods: ["따뜻한", "가벼운"], emoji: "🥬" },
        { name: "닭곰탕", cuisine: "한식", moods: ["따뜻한", "든든한"], emoji: "🍗" },
        { name: "오징어볶음", cuisine: "한식", moods: ["매운", "든든한"], emoji: "🦑" },
        { name: "코다리조림", cuisine: "한식", moods: ["매운", "든든한"], emoji: "🐟" },
        { name: "고등어구이정식", cuisine: "한식", moods: ["가벼운", "든든한"], emoji: "🐟" },
        { name: "김치볶음밥", cuisine: "한식", moods: ["든든한", "매운"], emoji: "🍚" },
        { name: "낙지볶음", cuisine: "한식", moods: ["매운", "든든한"], emoji: "🐙" },
        { name: "해물파전", cuisine: "한식", moods: ["든든한"], emoji: "🥞" },
        { name: "유산슬덮밥", cuisine: "중식", moods: ["든든한"], emoji: "🥡" },
        { name: "고추잡채", cuisine: "중식", moods: ["매운", "든든한"], emoji: "🫑" },
        { name: "팔보채", cuisine: "중식", moods: ["가벼운"], emoji: "🥢" },
        { name: "사천탕면", cuisine: "중식", moods: ["매운", "따뜻한"], emoji: "🍜" },
        { name: "군만두", cuisine: "중식", moods: ["가벼운"], emoji: "🥟" },
        { name: "탄탄면", cuisine: "중식", moods: ["매운", "따뜻한"], emoji: "🍜" },
        { name: "계란볶음밥", cuisine: "중식", moods: ["든든한"], emoji: "🍳" },
        { name: "해물누룽지탕", cuisine: "중식", moods: ["따뜻한", "든든한"], emoji: "🍲" },
        { name: "연어초밥세트", cuisine: "일식", moods: ["가벼운", "든든한"], emoji: "🍣" },
        { name: "카레우동", cuisine: "일식", moods: ["따뜻한", "든든한"], emoji: "🍛" },
        { name: "야키소바", cuisine: "일식", moods: ["든든한"], emoji: "🍝" },
        { name: "오코노미야키", cuisine: "일식", moods: ["든든한"], emoji: "🥞" },
        { name: "텐동", cuisine: "일식", moods: ["든든한"], emoji: "🍤" },
        { name: "치라시동", cuisine: "일식", moods: ["가벼운", "든든한"], emoji: "🐟" },
        { name: "니쿠우동", cuisine: "일식", moods: ["따뜻한", "든든한"], emoji: "🍜" },
        { name: "야끼토리덮밥", cuisine: "일식", moods: ["든든한"], emoji: "🍗" },
        { name: "규카츠", cuisine: "일식", moods: ["든든한"], emoji: "🥩" },
        { name: "냉소바", cuisine: "일식", moods: ["가벼운"], emoji: "🧊" },
        { name: "감바스 알 아히요", cuisine: "양식", moods: ["가벼운"], emoji: "🦐" },
        { name: "치킨 알프레도 파스타", cuisine: "양식", moods: ["든든한", "따뜻한"], emoji: "🍝" },
        { name: "미트볼 파스타", cuisine: "양식", moods: ["든든한"], emoji: "🍝" },
        { name: "버섯 크림 리조또", cuisine: "양식", moods: ["따뜻한", "든든한"], emoji: "🍚" },
        { name: "라클렛 플래터", cuisine: "양식", moods: ["든든한"], emoji: "🧀" },
        { name: "그릴드 치킨 플레이트", cuisine: "양식", moods: ["가벼운", "든든한"], emoji: "🍗" },
        { name: "토마토 수프 파스타", cuisine: "양식", moods: ["따뜻한"], emoji: "🍅" },
        { name: "클럽 샌드위치", cuisine: "양식", moods: ["가벼운"], emoji: "🥪" },
        { name: "쉬림프 타코샐러드", cuisine: "양식", moods: ["가벼운", "매운"], emoji: "🥗" },
        { name: "포크 립 플래터", cuisine: "양식", moods: ["든든한"], emoji: "🍖" },
        { name: "잔치국수", cuisine: "분식", moods: ["따뜻한", "가벼운"], emoji: "🍜" },
        { name: "비빔국수", cuisine: "분식", moods: ["가벼운", "매운"], emoji: "🌶️" },
        { name: "김치전", cuisine: "분식", moods: ["든든한"], emoji: "🥞" },
        { name: "주먹밥", cuisine: "분식", moods: ["가벼운"], emoji: "🍙" },
        { name: "떡만둣국", cuisine: "분식", moods: ["따뜻한", "든든한"], emoji: "🥟" },
        { name: "국물떡볶이", cuisine: "분식", moods: ["따뜻한", "매운"], emoji: "🍲" },
        { name: "라면정식", cuisine: "분식", moods: ["따뜻한", "든든한"], emoji: "🍜" },
        { name: "꼬치어묵", cuisine: "분식", moods: ["따뜻한", "가벼운"], emoji: "🍢" },
        { name: "치즈버거세트", cuisine: "패스트푸드", moods: ["든든한"], emoji: "🍔" },
        { name: "피쉬버거", cuisine: "패스트푸드", moods: ["가벼운"], emoji: "🐟" }
];
